-- Run this in Supabase -> SQL Editor.
-- This creates the vote table and permits anonymous visitors to submit
-- votes and read aggregate/raw vote rows.

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  poll text not null check (poll in ('faction','role','raid_ready','raid_nights','tradeskill')),
  choice text not null,
  created_at timestamptz not null default now()
);

alter table public.poll_votes enable row level security;

drop policy if exists "Anyone can submit poll votes" on public.poll_votes;
create policy "Anyone can submit poll votes"
on public.poll_votes
for insert
to anon
with check (
  (poll = 'faction' and choice in ('Alliance','Horde', 'No Preference'))
  or
  (poll = 'role' and choice in ('Tank','DPS','Heal'))
  or
  (poll = 'raid_ready' and choice in ('Yes','No','Fuck no, enjoy the journey'))
  or
  (poll = 'raid_nights' and choice in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'))
  or
  (poll = 'tradeskill' and choice in ('Blacksmithing','Leatherworking','Alchemy','Enchanting','Tailoring','Engineering','Gathering'))
);

drop policy if exists "Anyone can view poll results" on public.poll_votes;
create policy "Anyone can view poll results"
on public.poll_votes
for select
to anon
using (true);
